import Head from 'next/head';
import Link from 'next/link';

export default function Home({ data }) {
    return (
        <>
            <Head>
                <title>Events App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <header>
                {/* <nav>
                    <img src="" alt="" />
                    <a href="/">Home</a>
                    <a href="/events">Events</a>
                    <a href="/about-us">About Us</a>
                </nav> */}
            </header>
            <main>
                {data.map((eventCategory) => (
                    <div key={eventCategory.id}>
                        <Link href={`/events/${eventCategory.id}`}>
                            {/* <Image src={eventCategory.image} alt='' width={100} height={100} /> */}
                            {eventCategory.title}
                        </Link>
                    </div>
                ))}
            </main>
            <footer>&copy; {new Date().getFullYear()}</footer>
        </>
    );
}

export async function getStaticProps() {
    const { events_categories } = await import('../../data/data.json');

    return {
        props: {
            data: events_categories,
        },
    };
}
